sudo: required

services:
    - docker

language: php

php:
    - nightly

before_install:
    - cp .env.dist .env
    - docker-compose up -d --force-recreate --always-recreate-deps --renew-anon-volumes
    - docker-compose exec web composer install --no-interaction --prefer-dist --optimize-autoloader
    - docker-compose exec web php bin/console doctrine:database:drop --if-exists --force
    - docker-compose exec web php bin/console doctrine:database:create
    - docker-compose exec web php bin/console doctrine:migration:migrate -q

script:
    - docker-compose exec web php bin/phpunit --coverage-clover build/coverage/xml

after_script:
    - php vendor/bin/codacycoverage clover build/coverage/xml
