sudo: required

services:
    - docker
    - mysql

language: php

php:
    - nightly

before_install:
    - cp .env.test.dist .env
    - docker-compose up -d
    - docker-compose exec web composer install --no-interaction --prefer-dist --optimize-autoloader
    - docker-compose exec web php bin/console doctrine:database:drop --if-exists --force
    - docker-compose exec web php bin/console doctrine:database:create
    - docker-compose exec web php bin/console doctrine:migration:migrate -q

script:
    - docker-compose exec web php bin/phpunit --coverage-clover build/coverage/xml

after_script:
    - php vendor/bin/codacycoverage clover build/coverage/xml

deploy:
    provider: gae
    keyfile: keyfile.json
    project: park-queue-times
