language: php

php:
    - 7.2
    - nightly

matrix:
    allow_failures:
        - php: nightly

addons:
    sonarcloud:
        organization: "cvilleger-github"
        token:
            secure: $SONAR_TOKEN

before_install:
    - cp .env.test.dist .env
    - composer install --no-interaction --optimize-autoloader
    - php bin/console doctrine:schema:update --force

script:
    - php bin/phpunit --coverage-clover ./build/coverage/xml

after_script:
    - php vendor/bin/codacycoverage clover ./build/coverage/xml
    - sonar-scanner
