sudo: required

services:
    - docker

addons:
    sonarcloud:
        organization: "cvilleger-github"
        token:
            secure: $SONAR_TOKEN

language: php

php:
    - 7.2

before_install:
    - cp .env.test.dist .env
    - docker-compose up -d
    - docker-compose exec web composer install --no-interaction --prefer-dist --optimize-autoloader
    - docker-compose exec web php bin/console d:s:u --force

script:
    - docker-compose exec web php bin/phpunit --coverage-clover build/coverage/xml --coverage-xml build/coverage/phpunit

deploy:
    provider: script
    script: bash scripts/deploy.sh
    skip_cleanup: true

after_script:
    - php vendor/bin/codacycoverage clover build/coverage/xml
    - sonar-scanner
