version: "3"

services:

  web:
      image: webdevops/php-nginx-dev:7.2
      volumes:
          - ./:/app
      working_dir: /app
      env_file: .env
      environment:
          WEB_DOCUMENT_ROOT: /app/public
          PHP_DATE_TIMEZONE: "Europe/Paris"
